name: Lint
on:
    pull_request:
    push:
        branches:
            - master

jobs:
    lint:
        name: "Lint"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node 12
              uses: actions/setup-node@v1
              with:
                node-version: 12.x
            - run: npm i eslint eslint-plugin-react@latest
              name: Install dependencies
            - run: npm run lint
              name: JS Lint